// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.
import { endpoints, type EndpointOperation, type EndpointPathParam, type RequestByOperation, type ResponseByOperation } from "./endpoints.js";
import type { ContractTransport, ContractTransportRequest } from "./transport.js";

type ClientRequestShape = object;

export type ContractsClient = {
  [Operation in EndpointOperation]: (request: RequestByOperation[Operation]) => Promise<ResponseByOperation[Operation]>;
};

export function createContractsClient(transport: ContractTransport): ContractsClient {
  return {
    createProject: (request) => executeOperation("createProject", request, transport),
    getProject: (request) => executeOperation("getProject", request, transport),
    listProjects: (request) => executeOperation("listProjects", request, transport),
    updateProject: (request) => executeOperation("updateProject", request, transport),
    deleteProject: (request) => executeOperation("deleteProject", request, transport),
    openProjectWorkContext: (request) => executeOperation("openProjectWorkContext", request, transport),
    renewProjectWorkContext: (request) => executeOperation("renewProjectWorkContext", request, transport),
    createTask: (request) => executeOperation("createTask", request, transport),
    getTask: (request) => executeOperation("getTask", request, transport),
    listTasks: (request) => executeOperation("listTasks", request, transport),
    updateTask: (request) => executeOperation("updateTask", request, transport),
    deleteTask: (request) => executeOperation("deleteTask", request, transport),
    createSession: (request) => executeOperation("createSession", request, transport),
    getSession: (request) => executeOperation("getSession", request, transport),
    listSessions: (request) => executeOperation("listSessions", request, transport),
    updateSession: (request) => executeOperation("updateSession", request, transport),
    deleteSession: (request) => executeOperation("deleteSession", request, transport),
    createSkill: (request) => executeOperation("createSkill", request, transport),
    getSkill: (request) => executeOperation("getSkill", request, transport),
    listSkills: (request) => executeOperation("listSkills", request, transport),
    updateSkill: (request) => executeOperation("updateSkill", request, transport),
    deleteSkill: (request) => executeOperation("deleteSkill", request, transport),
    createAgent: (request) => executeOperation("createAgent", request, transport),
    getAgent: (request) => executeOperation("getAgent", request, transport),
    listAgents: (request) => executeOperation("listAgents", request, transport),
    updateAgent: (request) => executeOperation("updateAgent", request, transport),
    deleteAgent: (request) => executeOperation("deleteAgent", request, transport),
  };
}

async function executeOperation<Operation extends EndpointOperation>(
  operation: Operation,
  request: RequestByOperation[Operation],
  transport: ContractTransport,
): Promise<ResponseByOperation[Operation]> {
  const endpoint = endpoints[operation];
  const path = buildPath(endpoint.pathTemplate, endpoint.pathParams, request as ClientRequestShape);
  const body = buildJsonBody(endpoint.pathParams, endpoint.hasJsonBody, request as ClientRequestShape);
  const transportRequest: ContractTransportRequest = {
    operationName: endpoint.operationName,
    method: endpoint.method,
    path,
    body,
    headers: buildHeaders(endpoint.hasJsonBody),
  };

  return transport.send<ResponseByOperation[Operation]>(transportRequest);
}

function buildPath(
  pathTemplate: string,
  pathParams: readonly EndpointPathParam[],
  request: ClientRequestShape,
): string {
  const requestRecord = request as Record<string, unknown>;
  let path = pathTemplate;

  for (const pathParam of pathParams) {
    const value = requestRecord[pathParam.wireName];

    if (value === undefined || value === null) {
      throw new Error(`missing path parameter ${pathParam.wireName}`);
    }

    path = path.replace(`{${pathParam.wireName}}`, encodeURIComponent(String(value)));
  }

  return path;
}

function buildJsonBody(
  pathParams: readonly EndpointPathParam[],
  hasJsonBody: boolean,
  request: ClientRequestShape,
): Record<string, unknown> | undefined {
  if (!hasJsonBody) {
    return undefined;
  }

  const requestRecord = request as Record<string, unknown>;
  const pathParamNames = new Set(pathParams.map((pathParam) => pathParam.wireName));

  return Object.fromEntries(
    Object.entries(requestRecord).filter(([fieldName]) => !pathParamNames.has(fieldName)),
  );
}

function buildHeaders(hasJsonBody: boolean): Record<string, string> {
  if (!hasJsonBody) {
    return {};
  }

  return {
    "content-type": "application/json",
  };
}
